import { Hospital, Case, CaseRouting, Request, AuditEvent } from '../types/domain';

const NOW = Date.now();

export const SEED_HOSPITALS: Hospital[] = [
  {
    id: 'hospital_001',
    name: 'Apex Trauma & Emergency Centre',
    lat: 23.1245,
    lng: 72.5412,
    trauma_team_on_shift: true,
    specialists_on_call: ['cardiologist', 'orthopedist', 'general_surgeon', 'anesthetist', 'neurosurgeon'],
    icu_beds_free: 4,
    ventilators_free: 2,
    blood_stock: { 'O-': 6, 'O+': 14, 'A+': 12, 'A-': 3, 'B+': 10, 'B-': 2, 'AB+': 4, 'AB-': 1 },
    er_load_score: 2,
    accepts_scheme_patients: true,
    last_updated_at: NOW - 2 * 60 * 1000, // 2 min ago (fresh)
    reliability_score: 0.96,
    contact_number: '+91 79 2685 0101',
    operational_status: { icu: true, ventilator: true, blood: true },
  },
  {
    id: 'hospital_002',
    name: 'Metro Heart & Vascular Institute',
    lat: 23.1368,
    lng: 72.5534,
    trauma_team_on_shift: false,
    specialists_on_call: ['cardiologist', 'anesthetist', 'general_physician'],
    icu_beds_free: 6,
    ventilators_free: 4,
    blood_stock: { 'O-': 2, 'O+': 10, 'A+': 8, 'A-': 2, 'B+': 7, 'B-': 1, 'AB+': 5, 'AB-': 1 },
    er_load_score: 5, // High ER load
    accepts_scheme_patients: true,
    last_updated_at: NOW - 4 * 60 * 1000, // 4 min ago (fresh)
    reliability_score: 0.94,
    contact_number: '+91 79 2744 0202',
    operational_status: { icu: true, ventilator: true, blood: true },
  },
  {
    id: 'hospital_003',
    name: 'Sterling Multispecialty Hospital',
    lat: 23.1092,
    lng: 72.5621,
    trauma_team_on_shift: true,
    specialists_on_call: ['cardiologist', 'orthopedist', 'obgyn', 'pediatrician', 'general_surgeon', 'anesthetist'],
    icu_beds_free: 5,
    ventilators_free: 3,
    blood_stock: { 'O-': 5, 'O+': 16, 'A+': 14, 'A-': 3, 'B+': 12, 'B-': 2, 'AB+': 6, 'AB-': 2 },
    er_load_score: 2,
    accepts_scheme_patients: true,
    last_updated_at: NOW - 48 * 60 * 1000, // 48 min ago (unknown)
    reliability_score: 0.88,
    contact_number: '+91 79 2630 0505',
    operational_status: { icu: true, ventilator: true, blood: true },
  },
  {
    id: 'hospital_004',
    name: 'CityCare General Hospital',
    lat: 23.1189,
    lng: 72.5312,
    trauma_team_on_shift: false,
    specialists_on_call: ['general_surgeon', 'anesthetist', 'general_physician'],
    icu_beds_free: 3,
    ventilators_free: 0, // Ventilator constrained
    blood_stock: { 'O-': 1, 'O+': 6, 'A+': 4, 'B+': 5, 'AB+': 2 },
    er_load_score: 3,
    accepts_scheme_patients: true,
    last_updated_at: NOW - 5 * 60 * 1000, // 5 min ago (fresh)
    reliability_score: 0.82,
    contact_number: '+91 79 2650 0303',
    operational_status: { icu: true, ventilator: false, blood: true },
  },
  {
    id: 'hospital_005',
    name: 'Lifeline Emergency Hospital',
    lat: 23.155,
    lng: 72.522,
    trauma_team_on_shift: true,
    specialists_on_call: ['general_surgeon', 'orthopedist', 'anesthetist'],
    icu_beds_free: 2,
    ventilators_free: 2,
    blood_stock: { 'O-': 0, 'O+': 8, 'A+': 6, 'B+': 7, 'AB+': 3 }, // O- is 0
    er_load_score: 2,
    accepts_scheme_patients: false,
    last_updated_at: NOW - 22 * 60 * 1000, // 22 min ago (stale)
    reliability_score: 0.85,
    contact_number: '+91 79 2791 0404',
    operational_status: { icu: true, ventilator: true, blood: true },
  },
  {
    id: 'hospital_006',
    name: 'Sunrise Community Hospital',
    lat: 23.1415,
    lng: 72.5685,
    trauma_team_on_shift: false,
    specialists_on_call: ['general_physician', 'general_surgeon'],
    icu_beds_free: 0, // ICU exhausted
    ventilators_free: 1,
    blood_stock: { 'O+': 3, 'A+': 2, 'B+': 3 },
    er_load_score: 4,
    accepts_scheme_patients: true,
    last_updated_at: NOW - 7 * 60 * 1000, // 7 min ago (fresh)
    reliability_score: 0.78,
    contact_number: '+91 79 2810 0606',
    operational_status: { icu: false, ventilator: true, blood: true },
  },
  {
    id: 'hospital_007',
    name: 'Diamond Children & Pediatric Pavilion',
    lat: 23.1612,
    lng: 72.545,
    trauma_team_on_shift: false,
    specialists_on_call: ['pediatrician', 'anesthetist'],
    icu_beds_free: 4,
    ventilators_free: 3,
    blood_stock: { 'O-': 3, 'O+': 7, 'A+': 5, 'B+': 6, 'AB-': 2 },
    er_load_score: 1,
    accepts_scheme_patients: true,
    last_updated_at: NOW - 3 * 60 * 1000, // 3 min ago (fresh)
    reliability_score: 0.95,
    contact_number: '+91 79 2855 0707',
    operational_status: { icu: true, ventilator: true, blood: true },
  },
  {
    id: 'hospital_008',
    name: 'Mother & Child Care Specialty Hospital',
    lat: 23.098,
    lng: 72.535,
    trauma_team_on_shift: false,
    specialists_on_call: ['obgyn', 'pediatrician', 'anesthetist'],
    icu_beds_free: 3,
    ventilators_free: 2,
    blood_stock: { 'O-': 2, 'O+': 9, 'A+': 8, 'A-': 2, 'B+': 8, 'B-': 1, 'AB+': 3 },
    er_load_score: 2,
    accepts_scheme_patients: true,
    last_updated_at: NOW - 6 * 60 * 1000, // 6 min ago (fresh)
    reliability_score: 0.92,
    contact_number: '+91 79 2890 0808',
    operational_status: { icu: true, ventilator: true, blood: true },
  },
  {
    id: 'hospital_009',
    name: 'St. Jude Acute Care Clinic',
    lat: 23.128,
    lng: 72.518,
    trauma_team_on_shift: false,
    specialists_on_call: ['general_surgeon', 'cardiologist', 'anesthetist'],
    icu_beds_free: 1,
    ventilators_free: 1,
    blood_stock: { 'O-': 1, 'O+': 4, 'A+': 3, 'B+': 4 },
    er_load_score: 1,
    accepts_scheme_patients: true,
    last_updated_at: NOW - 1 * 60 * 1000, // 1 min ago (fresh)
    reliability_score: 0.99,
    contact_number: '+91 79 2920 0909',
    operational_status: { icu: true, ventilator: true, blood: true },
  },
  {
    id: 'hospital_010',
    name: 'Royal Crest Medical Center',
    lat: 23.175,
    lng: 72.56,
    trauma_team_on_shift: true,
    specialists_on_call: ['orthopedist', 'general_surgeon', 'anesthetist'],
    icu_beds_free: 4,
    ventilators_free: 3,
    blood_stock: { 'O-': 2, 'O+': 10, 'A+': 8, 'B+': 9 },
    er_load_score: 3,
    accepts_scheme_patients: false,
    last_updated_at: NOW - 15 * 60 * 1000, // 15 min ago (stale)
    reliability_score: 0.62,
    contact_number: '+91 79 2950 1010',
    operational_status: { icu: true, ventilator: true, blood: true },
  },
  {
    id: 'hospital_011',
    name: 'Greenfield District Hospital',
    lat: 23.085,
    lng: 72.555,
    trauma_team_on_shift: true,
    specialists_on_call: ['cardiologist', 'orthopedist', 'general_surgeon', 'obgyn', 'anesthetist'],
    icu_beds_free: 5,
    ventilators_free: 3,
    blood_stock: { 'O-': 4, 'O+': 12, 'A+': 10, 'A-': 2, 'B+': 11, 'AB+': 4 },
    er_load_score: 3,
    accepts_scheme_patients: true,
    last_updated_at: NOW - 8 * 60 * 1000, // 8 min ago (fresh)
    reliability_score: 0.89,
    contact_number: '+91 79 2980 1111',
    operational_status: { icu: true, ventilator: true, blood: true },
  },
  {
    id: 'hospital_012',
    name: 'Navjeevan Charitable Hospital',
    lat: 23.19,
    lng: 72.53,
    trauma_team_on_shift: false,
    specialists_on_call: ['general_physician'],
    icu_beds_free: 0,
    ventilators_free: 0,
    blood_stock: { 'O+': 2, 'A+': 1 },
    er_load_score: 4,
    accepts_scheme_patients: true,
    last_updated_at: NOW - 120 * 60 * 1000, // 120 min ago (unknown)
    reliability_score: null, // No history
    contact_number: '+91 79 2999 1212',
    operational_status: { icu: false, ventilator: false, blood: true },
  },
];

// Seed cases indexed for frontend stateStore
export const SEED_CASES: Record<string, Case> = {
  case_demo_cardiac_01: {
    id: 'case_demo_cardiac_01',
    created_at: NOW - 25 * 1000,
    category: 'cardiac',
    severity: 'red',
    need_profile: {
      specialists_needed: ['cardiologist'],
      capability_flags: ['ecg', 'cath_lab', 'icu'],
      blood_type_needed: null,
    },
    vitals_summary: 'Acute anterior wall STEMI, crushing chest pain, ST elevation V1-V4, SpO2 91%, Pulse 118, BP 144/92',
    onset_time: '25 minutes ago',
    treatment_administered: 'Aspirin 300mg chewed, Nitroglycerin sublingual, high-flow oxygen 4L/min',
    patient_basic_info: { age: 58, sex: 'male', name: 'Patient C-101' },
    incident_group_id: null,
    ambulance_location: { lat: 23.118, lng: 72.545 },
  },
  case_cardiac_01: {
    id: 'case_cardiac_01',
    created_at: NOW - 25 * 1000,
    category: 'cardiac',
    severity: 'red',
    need_profile: {
      specialists_needed: ['cardiologist'],
      capability_flags: ['ecg', 'cath_lab', 'icu'],
      blood_type_needed: null,
    },
    vitals_summary: 'Acute anterior wall STEMI, crushing chest pain, ST elevation V1-V4, SpO2 91%, Pulse 118, BP 144/92',
    onset_time: '25 minutes ago',
    treatment_administered: 'Aspirin 300mg chewed, Nitroglycerin sublingual, high-flow oxygen 4L/min',
    patient_basic_info: { age: 58, sex: 'male', name: 'Patient C-101' },
    incident_group_id: null,
    ambulance_location: { lat: 23.118, lng: 72.545 },
  },
  case_demo_trauma_01: {
    id: 'case_demo_trauma_01',
    created_at: NOW - 8 * 60 * 1000,
    category: 'trauma',
    severity: 'red',
    need_profile: {
      specialists_needed: ['orthopedist', 'general_surgeon'],
      capability_flags: ['trauma_team', 'icu'],
      blood_type_needed: 'O-',
    },
    vitals_summary: 'High-velocity road collision, open unstable pelvic fracture, active haemorrhage, BP 82/50, pulse 135',
    onset_time: '18 minutes ago',
    treatment_administered: 'Pelvic binder placed, 2x large-bore IVs, 1L normal saline running under pressure',
    patient_basic_info: { age: 34, sex: 'female', name: 'Patient T-102' },
    incident_group_id: null,
    ambulance_location: { lat: 23.112, lng: 72.558 },
  },
  case_trauma_02: {
    id: 'case_trauma_02',
    created_at: NOW - 8 * 60 * 1000,
    category: 'trauma',
    severity: 'red',
    need_profile: {
      specialists_needed: ['orthopedist', 'general_surgeon'],
      capability_flags: ['trauma_team', 'icu'],
      blood_type_needed: 'O-',
    },
    vitals_summary: 'High-velocity road collision, open unstable pelvic fracture, active haemorrhage, BP 82/50, pulse 135',
    onset_time: '18 minutes ago',
    treatment_administered: 'Pelvic binder placed, 2x large-bore IVs, 1L normal saline running under pressure',
    patient_basic_info: { age: 34, sex: 'female', name: 'Patient T-102' },
    incident_group_id: null,
    ambulance_location: { lat: 23.112, lng: 72.558 },
  },
  case_demo_obstetric_01: {
    id: 'case_demo_obstetric_01',
    created_at: NOW - 5 * 60 * 1000,
    category: 'obstetric',
    severity: 'red',
    need_profile: {
      specialists_needed: ['obgyn'],
      capability_flags: ['maternity', 'icu'],
      blood_type_needed: null,
    },
    vitals_summary: 'Severe pre-eclampsia with visual scotoma, BP 192/116, fetal bradycardia 95 bpm',
    onset_time: '35 minutes ago',
    treatment_administered: 'Magnesium sulfate IV loading dose given, left lateral tilt position, O2 via mask',
    patient_basic_info: { age: 28, sex: 'female', name: 'Patient O-103' },
    incident_group_id: null,
    ambulance_location: { lat: 23.168, lng: 72.522 },
  },
  case_demo_pediatric_01: {
    id: 'case_demo_pediatric_01',
    created_at: NOW - 6 * 60 * 1000,
    category: 'pediatric',
    severity: 'red',
    need_profile: {
      specialists_needed: ['pediatrician'],
      capability_flags: ['pediatric_emergency', 'icu'],
      blood_type_needed: null,
    },
    vitals_summary: 'Pediatric prolonged convulsive status epilepticus >15 min, SpO2 88%, cyanotic',
    onset_time: '20 minutes ago',
    treatment_administered: 'Midazolam buccal 10mg given, bag-valve mask ventilation, IV access secured',
    patient_basic_info: { age: 5, sex: 'male', name: 'Patient P-104' },
    incident_group_id: null,
    ambulance_location: { lat: 23.155, lng: 72.548 },
  },
};

export const SEED_ROUTINGS: Record<string, CaseRouting> = {
  case_demo_cardiac_01: {
    status: 'pending',
    active_request_id: 'req_demo_001',
    attempt_number: 1,
    accepted_hospital_id: null,
  },
  case_cardiac_01: {
    status: 'pending',
    active_request_id: 'req_demo_001',
    attempt_number: 1,
    accepted_hospital_id: null,
  },
  case_demo_trauma_01: {
    status: 'accepted',
    active_request_id: 'req_demo_002',
    attempt_number: 1,
    accepted_hospital_id: 'hospital_001',
  },
  case_trauma_02: {
    status: 'accepted',
    active_request_id: 'req_demo_002',
    attempt_number: 1,
    accepted_hospital_id: 'hospital_001',
  },
  case_demo_pediatric_01: {
    status: 'accepted',
    active_request_id: 'req_demo_004',
    attempt_number: 1,
    accepted_hospital_id: 'hospital_007',
  },
};

export const SEED_REQUESTS: Record<string, Request> = {
  req_demo_001: {
    id: 'req_demo_001',
    case_id: 'case_demo_cardiac_01',
    hospital_id: 'hospital_001',
    status: 'pending',
    sent_at: NOW - 15 * 1000,
    expires_at: NOW + 45 * 1000, // 45s remaining
    responded_at: null,
    attempt_number: 1,
    match_score_breakdown: {
      capability_match_pct: 100,
      distance_km: 1.2,
      distance_factor: 0.96,
      load_factor: 0.88,
      staleness_factor: 1.0,
      final_score: 95.8,
    },
    reason_shown_to_dispatcher: 'Rank 1 • Cath lab operational, interventional cardiologist on-call, 4 ICU beds ready',
  },
  req_apex_01: {
    id: 'req_apex_01',
    case_id: 'case_cardiac_01',
    hospital_id: 'hospital_001',
    status: 'pending',
    sent_at: NOW - 15 * 1000,
    expires_at: NOW + 45 * 1000,
    responded_at: null,
    attempt_number: 1,
    match_score_breakdown: {
      capability_match_pct: 100,
      distance_km: 1.2,
      distance_factor: 0.96,
      load_factor: 0.88,
      staleness_factor: 1.0,
      final_score: 95.8,
    },
    reason_shown_to_dispatcher: 'Rank 1 • Cath lab operational, interventional cardiologist on-call, 4 ICU beds ready',
  },
  req_demo_002: {
    id: 'req_demo_002',
    case_id: 'case_demo_trauma_01',
    hospital_id: 'hospital_001',
    status: 'accepted',
    sent_at: NOW - 7 * 60 * 1000,
    expires_at: NOW - 6 * 60 * 1000,
    responded_at: NOW - 6 * 60 * 1000 - 35 * 1000,
    attempt_number: 1,
    match_score_breakdown: {
      capability_match_pct: 100,
      distance_km: 1.6,
      distance_factor: 0.94,
      load_factor: 0.88,
      staleness_factor: 1.0,
      final_score: 94.6,
    },
    reason_shown_to_dispatcher: 'Rank 1 • Trauma team activated, 6 units O- blood in stock, OR-1 ready',
  },
  req_sterling_02: {
    id: 'req_sterling_02',
    case_id: 'case_trauma_02',
    hospital_id: 'hospital_001',
    status: 'accepted',
    sent_at: NOW - 7 * 60 * 1000,
    expires_at: NOW - 6 * 60 * 1000,
    responded_at: NOW - 6 * 60 * 1000 - 35 * 1000,
    attempt_number: 1,
    match_score_breakdown: {
      capability_match_pct: 100,
      distance_km: 1.6,
      distance_factor: 0.94,
      load_factor: 0.88,
      staleness_factor: 1.0,
      final_score: 94.6,
    },
    reason_shown_to_dispatcher: 'Rank 1 • Trauma team activated, 6 units O- blood in stock, OR-1 ready',
  },
};

export const SEED_AUDIT_LOGS: AuditEvent[] = [
  {
    id: 'audit_001',
    request_id: null,
    case_id: 'case_demo_cardiac_01',
    hospital_id: null,
    event_type: 'CASE_CREATED',
    timestamp: NOW - 25 * 1000,
    actor_type: 'ambulance',
    snapshot_of_data_at_decision_time: { category: 'cardiac', severity: 'red', age: 58 },
  },
  {
    id: 'audit_002',
    request_id: null,
    case_id: 'case_demo_cardiac_01',
    hospital_id: null,
    event_type: 'NEED_PROFILE_GENERATED',
    timestamp: NOW - 24 * 1000,
    actor_type: 'system',
    snapshot_of_data_at_decision_time: { specialists: ['cardiologist'], capabilities: ['ecg', 'cath_lab', 'icu'] },
  },
  {
    id: 'audit_003',
    request_id: null,
    case_id: 'case_demo_cardiac_01',
    hospital_id: 'hospital_001',
    event_type: 'MATCH_COMPUTED',
    timestamp: NOW - 20 * 1000,
    actor_type: 'system',
    snapshot_of_data_at_decision_time: { rank1: 'Apex Trauma & Emergency Centre', score: 95.8 },
  },
  {
    id: 'audit_004',
    request_id: 'req_demo_001',
    case_id: 'case_demo_cardiac_01',
    hospital_id: 'hospital_001',
    event_type: 'REQUEST_SENT',
    timestamp: NOW - 15 * 1000,
    actor_type: 'ambulance',
    snapshot_of_data_at_decision_time: { countdown_sec: 60, attempt: 1 },
  },
  {
    id: 'audit_005',
    request_id: 'req_demo_002',
    case_id: 'case_demo_trauma_01',
    hospital_id: 'hospital_001',
    event_type: 'REQUEST_ACCEPTED',
    timestamp: NOW - 6 * 60 * 1000,
    actor_type: 'hospital',
    snapshot_of_data_at_decision_time: { status: 'committed', unit: 'OR-1 Trauma Bay Reserved' },
  },
  {
    id: 'audit_006',
    request_id: null,
    case_id: 'case_demo_trauma_01',
    hospital_id: 'hospital_001',
    event_type: 'RESOURCE_HELD',
    timestamp: NOW - 5 * 60 * 1000,
    actor_type: 'system',
    snapshot_of_data_at_decision_time: { icu: 1, blood_O_neg: 2 },
  },
];
